<?php
    include "../part/head.php";
?>
    <h1 class="con">메인페이지입니다.</h1>
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est repellat mollitia temporibus rem cumque et in reprehenderit delectus facere explicabo! Modi accusantium voluptate est dignissimos inventore tempore quibusdam dolores culpa.
    Ducimus, totam voluptatum? Atque asperiores, dolorum aut ratione corporis quas? Error tempora, quis cum consequuntur similique praesentium, aliquid iste placeat harum nobis assumenda, dolor quasi tenetur molestias unde. Dolorum, magni.
    Quia dolore et deleniti fugiat officia ratione nesciunt eaque quo mollitia ut maxime perferendis nihil, nulla repellat veritatis ipsum dignissimos, veniam reprehenderit optio quidem tempore cupiditate molestiae amet? Perspiciatis, nam.
    Totam incidunt, quaerat aliquid explicabo, officiis similique impedit cumque excepturi nostrum, fuga facilis atque. Iste non temporibus et aperiam architecto iure, consequatur incidunt. Veniam quibusdam nostrum labore libero a facere.
    Ullam, veritatis amet quibusdam modi facilis quisquam nihil quod officiis alias, nesciunt deleniti. Tempora vitae atque quaerat fugit fugiat mollitia, aperiam earum illum eveniet ab ipsa reprehenderit nam animi recusandae.
    Omnis vel odit reiciendis? Eligendi, consequatur molestias corrupti ullam veritatis iusto enim minus quisquam veniam tempora quia atque minima quas recusandae accusantium dolores similique. Nesciunt ab vero voluptatum voluptatibus nemo?
    Ipsam iusto vitae doloremque. Commodi quam animi velit pariatur sint, accusamus, dolorem asperiores minima sunt culpa, deserunt eius iure quod dignissimos ullam! Culpa magnam unde similique. Asperiores impedit consequatur voluptatum.
    Voluptatum nemo quos laborum explicabo recusandae nostrum fugit neque qui optio facilis laudantium, quaerat doloribus reprehenderit hic sapiente nulla repellendus possimus excepturi illo odit ad consequatur eaque asperiores rem. Dolor.
    Quod unde facilis itaque sint mollitia, dolorum aut quaerat doloribus ut, veritatis reiciendis neque deleniti! Odio accusantium quos magni ad aspernatur mollitia esse, ea aut. Velit quisquam eveniet nesciunt. Odio?
    Iure, nam. Odio omnis iure nisi pariatur veritatis, unde, eveniet ab repellat provident, cupiditate hic ad sapiente odit suscipit maiores illum fugiat mollitia numquam nesciunt modi. Laboriosam, earum! Ab, laborum.
    Quaerat maiores, consectetur sint officia iusto asperiores et neque est atque soluta error, nam, commodi molestias unde. Mollitia iure minus consectetur harum, sequi vero quis cum aut vel exercitationem doloremque?
    Libero asperiores quam dicta! Atque quod a rerum. Pariatur tempore sequi, ullam facere, quod, soluta quisquam sapiente ducimus sit porro eum officia in architecto mollitia consequuntur? Eos ducimus magni deserunt.
    Totam, labore! Natus molestiae ratione nihil voluptas culpa error esse itaque labore fuga tenetur iste ab quibusdam, tempore aperiam officiis sequi voluptates ducimus nobis deserunt! Obcaecati, dicta sapiente! Placeat, explicabo.
    Sit doloribus cum minus eos dolorem a eligendi esse qui consectetur obcaecati non minima ratione fugit amet, earum libero provident porro nam veritatis praesentium quasi debitis nesciunt fuga! Ab, a.
    Accusamus aut quia voluptatibus, ducimus suscipit exercitationem modi doloribus, labore esse assumenda animi magni laborum veniam earum pariatur amet deserunt tenetur maxime. Officia quod ab commodi. Molestiae vel nihil quae?
    Totam dignissimos blanditiis ab praesentium sed incidunt facere sunt natus, laboriosam officiis a modi, voluptas consectetur enim reprehenderit laborum voluptatibus eos repudiandae excepturi aspernatur rem repellendus? Ipsam perspiciatis doloribus eaque!
    Earum facilis veritatis, nostrum sapiente nesciunt, eos impedit nihil doloremque temporibus aut porro cum quod ex harum doloribus repellendus molestiae rerum ad laboriosam. Voluptatum aliquam quod amet mollitia eius repellat!
    Ex non, quis velit illo ullam nesciunt odio molestias maiores commodi totam consectetur, officia architecto facere deleniti labore aliquam fuga praesentium blanditiis reprehenderit beatae cum saepe! Minus accusantium odit optio?
    Quam explicabo doloremque itaque, voluptas similique accusamus tempora reiciendis sequi sed autem, assumenda commodi neque id laboriosam doloribus facere velit, soluta voluptatem nobis? Ut, omnis quibusdam libero saepe cupiditate porro!
    Accusamus, laborum, iste neque accusantium commodi iusto inventore omnis nesciunt perspiciatis cupiditate, odio eos ratione repellat harum assumenda praesentium soluta alias impedit voluptas. Tempora distinctio fugiat ex nemo modi! Est.
    Dolore ipsum praesentium quisquam ullam, ducimus ex reprehenderit nostrum obcaecati neque asperiores suscipit facere culpa eius, omnis dolor ut quas, quod fugit qui similique? Facilis voluptatem illo eius laboriosam inventore.
    Error autem nihil consequatur quibusdam repellat incidunt molestiae dolores quaerat! Molestiae ut iusto mollitia. Nihil accusantium nobis maiores debitis corporis hic in praesentium nostrum. Fugiat accusamus quod ut iure quidem!
    Perferendis dolorum officiis itaque nesciunt reiciendis, modi natus blanditiis quibusdam illo vero ad voluptatibus fugit a eligendi vitae quo nemo fugiat sequi autem consequatur quasi quos! Laudantium, optio. Sed, sint.
    Nisi et corrupti vel aspernatur ipsum ea, quidem ullam, molestias vitae repudiandae harum voluptatibus laboriosam temporibus beatae animi deserunt. Distinctio sunt sit quasi dicta rerum fugit, eum animi quod laborum.
    Dolorum pariatur voluptatibus, nesciunt distinctio tenetur dicta officia nostrum accusamus, fuga magni eum quod reprehenderit adipisci, praesentium illum non sequi modi ipsa corrupti? Id natus nulla provident itaque! Dolores, sapiente!
    Corporis eum nostrum consequatur tempora sapiente ipsa tenetur hic odio dolorum ut optio, quis aperiam minima voluptates architecto nesciunt iusto pariatur libero non ipsam velit! Eligendi nobis rem assumenda autem?
    Ad, molestias odio. Assumenda, quo, facilis consectetur dolores dolor corrupti aperiam ut repellat molestias repudiandae sit earum expedita aspernatur eius suscipit soluta veritatis at optio blanditiis illo aliquid eligendi? Exercitationem.
    Expedita sit pariatur nihil ipsam quos animi incidunt cumque ad vel nisi veritatis sequi ducimus illo accusamus provident soluta, quaerat error facere odit dignissimos sapiente, fuga corrupti libero quo! Necessitatibus.
    Accusantium, eveniet. Consequatur autem hic veritatis blanditiis rerum, eligendi temporibus iste debitis itaque enim. Totam, iusto unde aperiam vero, ipsam tempora necessitatibus culpa aliquid labore nisi deleniti corrupti perspiciatis dolorem!
    Non sint maxime, deserunt odit maiores sequi officiis neque modi quisquam sed eveniet! Eum aliquid iusto eligendi quidem fugit eos doloremque saepe blanditiis. Tempore maxime laboriosam aspernatur fuga eveniet quam.
    Ad magni officia repellendus, ullam fugiat dignissimos, corporis eveniet exercitationem nesciunt optio atque adipisci sed hic fuga ipsam! Vel obcaecati, ullam nam eum molestiae voluptatum aliquam impedit exercitationem alias nemo.
    Deleniti, fugiat. Doloremque repellendus repudiandae officia. Esse eos maiores aspernatur quam amet alias perspiciatis repellendus? Placeat, deleniti, a nulla eligendi quisquam quibusdam sint quaerat ea totam sequi, ipsa minima deserunt.
    Non, consequuntur porro aliquid odit a expedita velit sunt cupiditate voluptas esse laborum natus ab nulla sint sequi obcaecati impedit voluptatibus et quibusdam aperiam dicta delectus? Obcaecati, cum magnam. Ex.
    Aliquam beatae sed mollitia repudiandae optio provident porro similique molestiae asperiores ut exercitationem vitae corrupti vero consequatur corporis amet aspernatur, dolorem iure! Dolorem aliquid ea, cumque facere iure fugiat eum.
    Hic provident tenetur consequuntur reprehenderit et laudantium libero expedita, nisi quaerat officiis commodi sed dolorum ad alias distinctio fugiat. Commodi quae in distinctio totam consequuntur? Vitae amet consequatur vero est.
    Quae soluta veritatis laborum architecto adipisci dicta incidunt, eius aliquid impedit recusandae voluptatum quidem similique veniam quis deleniti accusamus cumque voluptates numquam, modi corrupti ea porro officia voluptate. Obcaecati, voluptatibus.
    Illo dolores explicabo vel, quo eligendi error suscipit praesentium ipsum ea voluptatum fugiat fugit rem, est ipsam? Assumenda, quo doloribus tempore consequatur adipisci eaque voluptatum dicta, mollitia, atque commodi culpa.
    Enim beatae ducimus accusamus iste aliquam quo at laborum dolores temporibus quis, molestiae, deserunt vel nisi repellendus dolore, voluptas exercitationem minima. Quod est libero, aperiam quas deleniti rerum quo obcaecati.
    Quasi id perspiciatis tempora nihil ipsam harum nisi asperiores. Placeat ratione quidem beatae eaque quia aspernatur molestiae totam maiores. Hic magni quos similique veritatis ullam, aliquid voluptatibus eveniet asperiores quis!
    Explicabo animi minus sed, quisquam molestiae enim repellat, placeat modi voluptatum delectus impedit suscipit, nisi assumenda ipsum dignissimos necessitatibus. Quas corrupti, maiores at vel in atque fugiat quibusdam quam dolorum.</div>
    
<?php
    include "../part/foot.php";
?>